sudo: required
language: node_js
node_js:
  - "iojs"
  - "11"
services:
  - docker

before_install:
  - docker build -t tes -f Dockerfile.dev .

scripts:
  - docker run tes npm run test -- --coverage
