sudo: required

services:
  - docker
branches:
  only:
  - dev
before_install:
  - docker build -t amine/docker-react -f Dockerfile.dev .

scripts:
  - docker run amine/docker-react npm run test -- --coverage
